name: financeapp
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  bloc : ^8.1.2
  firebase_core: ^2.24.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  firebase_auth: ^4.15.3
  syncfusion_flutter_charts: ^23.2.7


  user_repository:
   path: packages/user_repository
  expense_repository:
   path: packages/expense_repository
  bills_repository:
   path: packages/bills_repository
  flutter_local_notifications: ^16.2.0
  flutter_screenutil: ^5.9.0
  firebase_messaging: ^14.7.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/



  